FROM node:24-alpine

WORKDIR /expense_tracker/frontend/react

COPY ./web/frontend/package.json /expense_tracker/frontend/react/

RUN yarn install

COPY ./web/frontend/ /expense_tracker/frontend/react/

EXPOSE 3000

CMD [ "yarn","dev" ]