FROM node:24-alpine

WORKDIR /expense_tracker/frontend/react

ADD ./web/frontend/package.json /expense_tracker/frontend/react/

RUN yarn install

ADD ./web/frontend/ /expense_tracker/frontend/react/

EXPOSE 80

CMD [ "yarn","dev" ]