name: "Expense Tracker CI/CD"

on:
  push:
    branches: ["**"]
    tags:
      - "v*"
  pull_request:
    branches: ["**"]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies for frontend
        run: |
          cd web/frontend
          yarn install

      - name: Check lint errors for frontend
        run: |
          cd web/frontend
          yarn lint

      - name: Check typeScript errors for frontend
        run: |
          cd web/frontend
          yarn tsc

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Install dependencies for backend
        run: |
          cd web/backend
          pip install -r requirements.txt

      - name: Errors check for backend
        run: |
          cd web/backend
          ruff check .

  build-docker-frontend:
    runs-on: ubuntu-latest
    environment: Expense-Tracker
    if: startsWith(github.ref, 'refs/tags/')
    needs: [frontend-test, backend-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web/frontend
          file: ./web/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend:${{ github.ref_name }}

  build-docker-backend:
    runs-on: ubuntu-latest
    environment: Expense-Tracker
    if: startsWith(github.ref, 'refs/tags/')
    needs: [frontend-test, backend-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web/backend
          file: ./web/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/expense-tracker-backend:${{ github.ref_name }}
